### PR TITLE
Add img block and quote paragraph. Test included.

### PR DESCRIPTION
**Pull request by andysim3d**

### CODE REVIEW

**Review by jinglongwu — COMMENTED** [review]
Should we leave only Element, Block and Paragraph in this file as super classes, and other styles should have their own .py file and test? Check my PR.

**Comment by andysim3d** [comment]
> Should we leave only Element, Block and Paragraph in this file as super classes, and other styles should have their own .py file and test? Check my PR.

I personally don't like too many python files in one project, especially logically they are closed to each other.

**Comment by VCneverdie** [comment]
> > Should we leave only Element, Block and Paragraph in this file as super classes, and other styles should have their own .py file and test? Check my PR.
> 
> I personally don't like too many python files in one project, especially logically they are closed to each other.

I also prefer to separate classes into files, especially it will reduce code conflict.

**Comment by jinglongwu** [comment]
> > > Should we leave only Element, Block and Paragraph in this file as super classes, and other styles should have their own .py file and test? Check my PR.
> > 
> > 
> > I personally don't like too many python files in one project, especially logically they are closed to each other.
> 
> I also prefer to separate classes into files, especially it will reduce code conflict.

second. it was my thought as well - reduce merge conflicts.

**Comment by jinglongwu** [comment]
Let's determine which code structure to go with now, then I will update my PR correspondingly.

**Comment by andysim3d** [comment]
> Let's determine which code structure to go with now, then I will update my PR correspondingly.

I update a new pr to split them into multiple files. let's stick to it.

**Comment by andysim3d** [comment]
reworked

**Pull request closed without merging**
